#!/usr/bin/env sh

version="0.1.0"

# Shows the usage
function usage() {
  cat << EOS
Usage:
  wifi-password [options] [network-name]
Options:
  -v, --version    Output version
  -h, --help       Show the usage.
Examples:
  wifi-password foo-network
EOS
}

getOS() {
  case "`uname -s`" in
    Darwin)
      OS_NAME='osx' ;;
    Linux)
      OS_NAME='linux' ;;
    CYGWIN* | MINGW* | MSYS*)
      OS_NAME='windows' ;;
    *)
      OS_NAME='unknown' ;;
  esac
}

case $1 in
  -V | --version)
    echo ${version}
    exit
  ;;
  -h | --help)
    usage
    exit
  ;;
  *)
    usage
    exit
  ;;
esac

getOS
echo ${OS_NAME}
