#!/usr/bin/env sh

version="0.1.0"

# Shows the usage
function usage() {
  cat << EOS
Usage:
  wifi-password [options]
Options:
  -i      - SSID of the network you want to get the password
  -a      - Get the list of all network with their passwords
  -v      - Output version
  -h      - Show the usage
Examples:
  wifi-password -i foo-network
EOS
}

# Get the operating system type
getOS() {
  case "`uname -s`" in
    Darwin)
      OS_NAME='osx'
    ;;
    Linux)
      OS_NAME='linux'
    ;;
    CYGWIN* | MINGW* | MSYS*)
      OS_NAME='windows'
    ;;
    *)
      OS_NAME='unknown'
    ;;
  esac
}

while getopts "hiv" opt; do
  case ${opt} in
    h | i | v)
      declare option_${opt}=${OPTARG:-0}
    ;;
    \?)
      echo >&2 "Use 'wifi-password -h' to see usage info"
      exit 1
    ;;
  esac
done

shift $((OPTIND-1))

# If number of arguments is 0 then exit
if [[ $# -gt 0 ]]; then
  echo >&2 "Invalid arguments: $@"
  echo >&2 "Use 'wifi-password -h' to see usage info"
  exit 1
fi

# Main script
if [[ ${option_h} ]]; then
  usage
  exit 0
fi
